### PR TITLE
fix vdr-softhddevice for glibc v2.37 release

### PR DESCRIPTION
**Pull request by olebowle**

### CODE REVIEW

**Comment by M-Reimer** [comment]
Can you please prepend $pkgname on the patch filename? Make it something like "$pkgname-glibc.patch". I autobuild with a global source directory so names have to be unique.

**Comment by olebowle** [comment]
fixed

**Review by M-Reimer — APPROVED** [review]

**Comment by M-Reimer** [comment]
I can't merge currently for whatever reason. Controls in GitHub are missing. Will check again tomorrow.

**Comment by M-Reimer** [comment]
Worked now. I don't know why the controls where missing yesterday... Thanks for your support.

**Comment by olebowle** [comment]
Can you please push it to the AUR as well?

**Comment by M-Reimer** [comment]
Done. I can easily merge pull requests on my smartphone but to sync over to AUR requires me to boot my PC. So sorry if AUR updates take longer.

**Pull request merged**
