### PR TITLE
Update vdr-softhddevice and vdr-skindesigner

### PR DESCRIPTION
**Pull request by olebowle**

### CODE REVIEW

**Comment by M-Reimer** [comment]
Your Skindesigner update is perfect. Thanks for that.

Does your softhddevice modification actually change something? Is the patch different from the other repo (which, btw, are both orphaned).

Please don't change repo-make.conf. I'm OK with an Upgrade but I won't import ffmpeg2.8 (a proper fix would be if someone actually fixes softhddevice to properly build against up-to-date ffmpeg).

Maybe the "proper fix" for the softhddevice problem would be to completely delete it. An alternative output plugin is in development:
https://github.com/jojo61/vdr-plugin-softhdcuvid

**Comment by olebowle** [comment]
The softhddevice from current git couldn't be built, because the patch tried to apply stuff, which was already there in the projects.vdr-developer.org repo.

That is why I chose to only use [softhddevice-openglosd](https://github.com/louisbraun/softhddevice-openglosd). I know both of them are kind of outdated. But at least the package can built again and it works, I have it running in production (vdr-2.4.0).

I agree that vdr-plugin-softhdcuvid would be better, but according to the README it needs `NVIDIA driver 410.48 or newer`, which won't support older graphics cards (like my gt430).

I'll adjust the PR.

**Comment by olebowle** [comment]
> The softhddevice from current git couldn't be built, because the patch tried to apply stuff, which was already there in the projects.vdr-developer.org repo.
> 
I just realized this shouldn't have happend, since a commit id is used from the old repo. I might try to reproduce what the issue was when building the package. But I probably won't be able to do so within the next two weeks. But I guess this PR is not time critical.

**Comment by M-Reimer** [comment]
No. Take your time. I don't use it anyway. I would just update it according to your pull request and sync it up to AUR.
Just don't touch repo-make.conf in this case, as this would affect my autobuild process and I don't want to build an old ffmpeg.

**Comment by olebowle** [comment]
Okay, I unexpectedly got remote access to the vdr machine. I am actually able to build the package from git and it also works. Not sure what I did wrong the last time. So nothing to do for softhddevice then, there is only skindesigner to be updated. I already adjusted the PR accordingly.

**Pull request merged**
