### PR TITLE
Add lcdproc plugin for SoundGraph Imon VFD displays.

### PR DESCRIPTION
**Pull request by tmn505**
Reason: The imonlcd plugin doesn't support VFD displays.

### CODE REVIEW

**Comment by CReimer** [comment]
You're adding an udev rule for idProduct ffdc. Does this mean this line in the udev rule for the imonlcd plugin is obsolete?

https://github.com/VDR4Arch/vdr4arch/blob/master/plugins/vdr-imonlcd/92-imonlcd.rules#L2

**Comment by tmn505** [comment]
I was wondering about this also, it's my use case, and I don't think it's making it obsolete because imonlcd rule adds more informations. Depends on display, users usually will install imonlcd or lcdproc so I don't think it'll conflict. On the other side lcdproc supports much more displays and adding only the rule for one display doesn't seem to be okay. I can remove this rule and add message about it when installing. Should I do that?

**Comment by CReimer** [comment]
I'm still a bit confused.
The imonlcd plugin can make use the Imon VFD you're using, but you prefer to use lcdproc instead, right?

**Comment by tmn505** [comment]
The opposite, if I could use it, I'd do that, look on "Hinweis" here http://www.vdr-wiki.de/wiki/index.php/Imonlcd-plugin.

**Pull request merged**
